-- Advent Pro database entry point
--
-- The former combined schema has been replaced with ordered migrations.
-- Run every SQL file in `supabase/migrations/` in numeric order, or use:
--
--   supabase link --project-ref YOUR_PROJECT_REF
--   supabase db push
--
-- Current order:
--   001_content_foundation.sql
--   002_accounts_and_roles.sql
--   003_security_policies_and_seeds.sql
--
-- See `supabase/MIGRATIONS.md`. Future changes must be added as 004, 005,
-- and so on. Do not edit a migration after it has been deployed.
