-- Advent Pro database entry point
--
-- The former combined schema has been replaced with ordered migrations.
-- Run every SQL file in `supabase/migrations/` in numeric order, or use:
--
--   supabase link --project-ref YOUR_PROJECT_REF
--   supabase db push
--
-- Current order:
--   001_content_foundation.sql
--   002_accounts_and_roles.sql
--   003_security_policies_and_seeds.sql
--   004_study_engagement.sql
--   005_api_role_privileges.sql
--   006_api_privileges_and_admin_provisioning.sql
--   007_song_catalog_privileges.sql
--   008_media_module.sql through 018_fix_donation_daily_totals_decrement.sql
--   019_dynamic_content_categories.sql
--   020_publish_collaboration_categories.sql
--
-- See `supabase/MIGRATIONS.md`. Future changes must use the next number.
-- Do not edit a migration after it has been deployed.
