import { Ionicons } from "@expo/vector-icons";
import { Stack, useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { useAppTheme } from "@/hooks/use-app-theme";
import { useAuth } from "@/src/auth/AuthContext";
import { getPlaylist, listPlaylistSongs, removeSongFromPlaylist, syncPersonalContent, type PlaylistSong, type SongPlaylist } from "@/src/features/personal/personalService";

export default function PlaylistDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const auth = useAuth(); const { colors, fontFamily } = useAppTheme();
  const [playlist, setPlaylist] = useState<SongPlaylist | null>(null); const [songs, setSongs] = useState<PlaylistSong[]>([]);
  const load = useCallback(async () => { if (!id) return; const playlistId = String(id); const [row, items] = await Promise.all([getPlaylist(playlistId, auth.user?.id ?? null), listPlaylistSongs(playlistId)]); setPlaylist(row); setSongs(items); }, [auth.user?.id, id]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const remove = (song: PlaylistSong) => Alert.alert("Remove from playlist?", song.title, [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void (async () => { await removeSongFromPlaylist(String(id), song.id); if (auth.user?.id) void syncPersonalContent(auth.user.id); await load(); })() }]);
  return <View style={[styles.container, { backgroundColor: colors.background }]}><Stack.Screen options={{ headerShown: false }} /><View style={[styles.header, { backgroundColor: colors.card, borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text} /></Pressable><View style={styles.headerCopy}><Text numberOfLines={1} style={[styles.title, { color: colors.text, fontFamily }]}>{playlist?.title || "Playlist"}</Text><Text style={[styles.subtitle, { color: colors.mutedText, fontFamily }]}>{songs.length} {songs.length === 1 ? "song" : "songs"} · playlist order</Text></View></View>
    {!!songs.length && <View style={[styles.tip, { backgroundColor: `${colors.tint}10` }]}><Ionicons name="play-skip-forward-outline" size={18} color={colors.tint} /><Text style={[styles.tipText, { color: colors.text, fontFamily }]}>Open the first song, then use Next to move through this list.</Text></View>}
    <FlatList data={songs} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, !songs.length && styles.emptyList]} renderItem={({ item, index }) => <Pressable onPress={() => router.push({ pathname: "/song/[id]", params: { id: item.id, playlist: String(id) } })} style={({ pressed }) => [styles.card, { backgroundColor: colors.card, borderColor: colors.border }, pressed && { opacity: .7 }]}><View style={[styles.position, { backgroundColor: `${colors.tint}12` }]}><Text style={[styles.positionText, { color: colors.tint, fontFamily }]}>{index + 1}</Text></View><View style={styles.songCopy}><Text numberOfLines={1} style={[styles.songTitle, { color: colors.text, fontFamily }]}>{item.title}</Text><Text style={[styles.meta, { color: colors.mutedText, fontFamily }]}>Hymn #{item.hymnNumber} · {item.language}</Text></View><Pressable hitSlop={10} onPress={() => remove(item)}><Ionicons name="remove-circle-outline" size={22} color={colors.mutedText} /></Pressable></Pressable>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="musical-note-outline" size={56} color={colors.tint} /><Text style={[styles.emptyTitle, { color: colors.text, fontFamily }]}>This playlist is empty</Text><Text style={[styles.emptyText, { color: colors.mutedText, fontFamily }]}>Open any song and tap “Add to playlist.”</Text><Pressable onPress={() => router.push("/categories")} style={[styles.button, { backgroundColor: colors.tint }]}><Text style={styles.buttonText}>Browse songs</Text></Pressable></View>} />
  </View>;
}

const styles = StyleSheet.create({ container: { flex: 1 }, header: { minHeight: 68, borderBottomWidth: 1, paddingHorizontal: 13, flexDirection: "row", alignItems: "center" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, headerCopy: { flex: 1, marginLeft: 4 }, title: { fontSize: 19, fontWeight: "900" }, subtitle: { fontSize: 11, marginTop: 2 }, tip: { margin: 16, marginBottom: 6, borderRadius: 13, padding: 12, flexDirection: "row", alignItems: "center", gap: 9 }, tipText: { flex: 1, fontSize: 12, lineHeight: 17, fontWeight: "600" }, list: { padding: 16, paddingBottom: 42, gap: 10 }, emptyList: { flexGrow: 1 }, card: { minHeight: 72, borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 12 }, position: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, positionText: { fontSize: 17, fontWeight: "900" }, songCopy: { flex: 1 }, songTitle: { fontSize: 15, fontWeight: "800" }, meta: { fontSize: 11, marginTop: 4 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30, paddingBottom: 80 }, emptyTitle: { fontSize: 20, fontWeight: "900", marginTop: 12 }, emptyText: { fontSize: 13, marginTop: 6, textAlign: "center" }, button: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 13, marginTop: 17 }, buttonText: { color: "#fff", fontWeight: "800" } });

