import { Ionicons } from "@expo/vector-icons";
import { Stack, useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAppTheme } from "@/hooks/use-app-theme";
import { useAuth } from "@/src/auth/AuthContext";
import { createPlaylist, deletePlaylist, listPlaylists, syncPersonalContent, type SongPlaylist } from "@/src/features/personal/personalService";

export default function PlaylistsScreen() {
  const router = useRouter(); const auth = useAuth(); const { colors, fontFamily } = useAppTheme();
  const [playlists, setPlaylists] = useState<SongPlaylist[]>([]); const [creating, setCreating] = useState(false); const [title, setTitle] = useState("");
  const load = useCallback(async () => { setPlaylists(await listPlaylists(auth.user?.id ?? null)); }, [auth.user?.id]);
  useFocusEffect(useCallback(() => { void (async () => { if (auth.user?.id) await syncPersonalContent(auth.user.id); await load(); })(); }, [auth.user?.id, load]));
  const create = async () => { try { const id = await createPlaylist(auth.user?.id ?? null, title); setTitle(""); setCreating(false); if (auth.user?.id) void syncPersonalContent(auth.user.id); router.push({ pathname: "/playlists/[id]", params: { id } }); } catch (error) { Alert.alert("Playlist title", (error as Error).message); } };
  const remove = (item: SongPlaylist) => Alert.alert("Delete playlist?", `The songs stay in the songbook; only “${item.title}” is removed.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void (async () => { await deletePlaylist(item.id); if (auth.user?.id) void syncPersonalContent(auth.user.id); await load(); })() }]);
  return <View style={[styles.container, { backgroundColor: colors.background }]}><Stack.Screen options={{ headerShown: false }} />
    <View style={styles.heading}><View style={styles.headingCopy}><Text style={[styles.title, { color: colors.text, fontFamily }]}>Song playlists</Text><Text style={[styles.subtitle, { color: colors.mutedText, fontFamily }]}>Build an order, then sing straight through.</Text></View><Pressable onPress={() => setCreating(true)} style={[styles.add, { backgroundColor: colors.tint }]}><Ionicons name="add" size={25} color="#fff" /></Pressable></View>
    {!auth.user && <Pressable onPress={() => router.push("/account")} style={[styles.banner, { borderColor: `${colors.tint}55`, backgroundColor: `${colors.tint}10` }]}><Ionicons name="cloud-offline-outline" size={20} color={colors.tint} /><Text style={[styles.bannerText, { color: colors.text, fontFamily }]}>Playlists work offline. Sign in to sync them.</Text><Ionicons name="chevron-forward" size={18} color={colors.tint} /></Pressable>}
    <FlatList data={playlists} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, !playlists.length && styles.emptyList]} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/playlists/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.card, { backgroundColor: colors.card, borderColor: colors.border }, pressed && { opacity: .7 }]}><View style={[styles.icon, { backgroundColor: `${colors.tint}12` }]}><Ionicons name="musical-notes" size={25} color={colors.tint} /></View><View style={styles.cardCopy}><Text numberOfLines={1} style={[styles.cardTitle, { color: colors.text, fontFamily }]}>{item.title}</Text><Text style={[styles.count, { color: colors.mutedText, fontFamily }]}>{item.songCount} {item.songCount === 1 ? "song" : "songs"}{item.syncState === "pending" ? " · waiting to sync" : ""}</Text></View><Pressable hitSlop={10} onPress={() => remove(item)}><Ionicons name="trash-outline" size={19} color={colors.mutedText} /></Pressable></Pressable>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="list-circle-outline" size={70} color={colors.tint} /><Text style={[styles.emptyTitle, { color: colors.text, fontFamily }]}>Create a singing order</Text><Text style={[styles.emptyText, { color: colors.mutedText, fontFamily }]}>Make as many playlists as you need—for Sabbath, choir practice, or special programs.</Text><Pressable onPress={() => setCreating(true)} style={[styles.emptyButton, { backgroundColor: colors.tint }]}><Text style={styles.emptyButtonText}>New playlist</Text></Pressable></View>} />
    <Modal visible={creating} transparent animationType="fade" onRequestClose={() => setCreating(false)}><Pressable style={styles.backdrop} onPress={() => setCreating(false)}><Pressable style={[styles.dialog, { backgroundColor: colors.card, borderColor: colors.border }]} onPress={(event) => event.stopPropagation()}><Text style={[styles.dialogTitle, { color: colors.text, fontFamily }]}>New playlist</Text><TextInput autoFocus value={title} onChangeText={setTitle} onSubmitEditing={() => void create()} placeholder="e.g. Sabbath morning" placeholderTextColor={colors.subtleText} style={[styles.input, { color: colors.text, borderColor: colors.border, fontFamily }]} /><View style={styles.actions}><Pressable onPress={() => setCreating(false)} style={styles.action}><Text style={{ color: colors.text }}>Cancel</Text></Pressable><Pressable onPress={() => void create()} style={[styles.action, { backgroundColor: colors.tint }]}><Text style={styles.primary}>Create</Text></Pressable></View></Pressable></Pressable></Modal>
  </View>;
}

const styles = StyleSheet.create({
  container: { flex: 1 }, heading: { padding: 20, paddingTop: 25, flexDirection: "row", alignItems: "center" }, headingCopy: { flex: 1 }, title: { fontSize: 28, fontWeight: "900" }, subtitle: { fontSize: 13, marginTop: 3 }, add: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, banner: { marginHorizontal: 20, marginBottom: 14, padding: 13, borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 10 }, bannerText: { flex: 1, fontSize: 12, fontWeight: "700" }, list: { paddingHorizontal: 20, paddingBottom: 40, gap: 11 }, emptyList: { flexGrow: 1 }, card: { minHeight: 78, borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: "row", alignItems: "center", gap: 13 }, icon: { width: 49, height: 49, borderRadius: 15, alignItems: "center", justifyContent: "center" }, cardCopy: { flex: 1 }, cardTitle: { fontSize: 16, fontWeight: "800" }, count: { fontSize: 11, marginTop: 4 }, empty: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 30, paddingBottom: 80 }, emptyTitle: { fontSize: 20, fontWeight: "900", marginTop: 12 }, emptyText: { fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 7 }, emptyButton: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 13, marginTop: 18 }, emptyButtonText: { color: "#fff", fontWeight: "800" }, backdrop: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "rgba(2,6,23,.55)" }, dialog: { borderWidth: 1, borderRadius: 20, padding: 18 }, dialogTitle: { fontSize: 20, fontWeight: "900", marginBottom: 14 }, input: { minHeight: 48, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12 }, actions: { flexDirection: "row", justifyContent: "flex-end", gap: 9, marginTop: 16 }, action: { minHeight: 42, paddingHorizontal: 16, borderRadius: 11, alignItems: "center", justifyContent: "center" }, primary: { color: "#fff", fontWeight: "800" },
});

