import type { Metadata } from "next";
export const metadata: Metadata = { title: "Terms of Service | Advent Pro", description: "Advent Pro terms of service" };
const sections=[
 ["Accounts and eligibility","You may use core reading features without an account. For account and community features, provide accurate information, keep your password and device secure, and report unauthorized access. You are responsible for activity under your account. New accounts begin with the Reader role; authorized administrators may assign or revoke other roles."],
 ["Community rules","Comments, reports, likes, and other interactions must be respectful and lawful. Do not harass, threaten, impersonate, spam, manipulate engagement or view counts, post malicious links, spread deliberately harmful misinformation, or infringe another person's privacy or rights. Do not bypass security, scrape abusively, reverse engineer protected parts of the service, or disrupt availability."],
 ["Moderation","Advent Pro may review reports and may hide, edit, preserve, or remove comments or other material; restrict interactions; and suspend accounts when reasonably necessary to enforce these terms, protect users, comply with law, or secure the service. Moderation and automated spam controls may not identify every problem."],
 ["Contributions and licence","You retain rights you hold in material you submit. You grant Advent Pro and Advent Nuru Tech a worldwide, non-exclusive, royalty-free licence to host, store, reproduce, format, adapt for technical display, translate, distribute, and display that material as needed to operate, improve, and promote the service. You confirm you have the rights and permissions needed to submit it. Editors may correct, reject, unpublish, or remove contributed resources."],
 ["Spiritual resources","Hymns, Bible resources, studies, videos, Shorts, recommendations, and community content are provided for worship, education, and personal study. Contributor and linked-media views do not necessarily represent Advent Pro. Verify important information and do not use the service as medical, legal, financial, emergency, or professional advice."],
 ["Voluntary support and external services","Support the Work is an optional, one-time donation processed by Paystack. It is not a subscription, purchase, membership, or requirement for using Advent Pro, and it does not unlock or restrict any feature or content. Payment availability and processing are subject to Paystack's terms and privacy practices. Some media is hosted by YouTube and plays through its embedded player, so YouTube's terms and privacy practices also apply."],
 ["Engagement and recommendations","View, like, share, and comment totals and personalized or popular-study rankings are service features. Counts may be delayed, deduplicated, moderated, reset, or corrected and are not guaranteed to be exact. Do not attempt to inflate or manipulate them."],
 ["Copyright and reports","Respect authors, ministries, publishers, video owners, and applicable licences. Report infringement or content concerns through adventnurutech.xyz, identifying the material and the basis for your request. We may remove or restrict disputed material while reviewing it."],
 ["Offline use and updates","Downloaded or bundled content may remain available offline. When connected, the app may receive new resources, corrections, withdrawals, rankings, media details, and compatibility or security changes without an app-store release. Application changes may still require an app-store update, and online or embedded-media features require a suitable connection."],
 ["Account deletion and termination","You may stop using the service and request account deletion. A request is queued for processing and is not completed merely by uninstalling the app. We may retain limited security, legal, audit, dispute, and backup records where permitted or required. We may restrict or terminate access that violates these terms, creates risk, or must be restricted by law."],
 ["Service availability and liability","The service is provided on an as-available basis. We do not promise uninterrupted access, permanent availability of third-party videos, or that every resource, translation, recommendation, count, or community post is complete, accurate, or error-free. To the extent permitted by law, Advent Pro and Advent Nuru Tech are not liable for indirect, incidental, special, consequential, or punitive loss. Nothing excludes rights or liability that cannot legally be excluded."],
 ["Changes and contact","We may update these terms as features, providers, or legal requirements change. We will revise the effective date and provide reasonable additional notice for material changes. Questions, reports, and account requests can be submitted through https://adventnurutech.xyz."],
];
export default function TermsPage(){return <main className="legal-page"><h1>Advent Pro Terms of Service</h1><p className="legal-date">Effective August 25, 2026</p><p>By using Advent Pro, you agree to these terms. If you do not agree, do not create an account or use the online services. Core content may remain available offline where installed.</p>{sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}<nav className="legal-links" aria-label="Advent Pro legal resources"><a href="/privacy">Privacy Policy</a><a href="/account-deletion">Request account deletion</a><a href="mailto:adventnurutech@gmail.com">Contact Advent Nuru Tech</a></nav></main>}
