import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy | Advent Pro", description: "Advent Pro privacy policy" };
const sections = [
  ["Account information", "You can read core resources without an account. If you create one, we process your email address, display name, account identifier, roles, authentication and session records, and account-security events. Supabase handles passwords and authentication tokens; Advent Pro does not receive your plaintext password."],
  ["Community and administrative content", "We process study and media comments, likes, comment reports, moderation status, content contributions, publication records, role assignments, deletion requests, and audit records. Your display name and visible comments are shown to other users. Reports, email addresses, role-management details, and audit records are limited to you or authorized administrators as appropriate."],
  ["Viewing activity and recommendations", "To count views, limit duplicate counts, rank popular content, and recommend studies, we process the study or media item viewed, timestamps, a random app session identifier, media watch duration, and your account identifier when signed in. Anonymous session identifiers are not intended to identify you by name, but they are still usage data."],
  ["Offline and device storage", "Songs, studies, Bible versions, search indexes, settings, daily-verse state, authentication sessions, and cached media details may be stored locally using the app database or device storage. Clearing app data or uninstalling removes local data, but it does not by itself delete synchronized account or community data."],
  ["Embedded media and external services", "Advent Pro uses Supabase for authentication, database, synchronization, and email delivery. YouTube videos and Shorts play through an embedded YouTube player; Google or YouTube may receive network, device, cookie or similar identifier, and playback information under their own terms and privacy policy. Links for donations, websites, calls, WhatsApp, and sharing open third-party services that process information you choose to send under their own policies. Advent Pro does not read your contacts, call history, WhatsApp messages, or payment-card details through these actions."],
  ["How we use information", "We use information to operate accounts and community features, provide and synchronize content, count engagement, personalize or rank discovery, prevent spam and abuse, moderate reports, secure and administer the service, respond to support and deletion requests, and comply with legal obligations. We do not sell personal information or use it for third-party behavioral advertising."],
  ["When information is shared", "We disclose information to service providers that operate the service, to other users when you post public community content, when you deliberately share content through another app, when required by law, or when necessary to protect users, rights, and service security. Authorized administrators can access information needed for their assigned duties."],
  ["Retention and account deletion", "We keep information only as long as reasonably needed for the purposes above, including security, moderation, disputes, legal obligations, backups, and audit integrity. In-app deletion creates a pending request and signs you out; an authorized administrator or server process must complete deletion of the Supabase Auth account and associated personal data. Request deletion in Advent Pro under Settings, Account & access, or through our public account-deletion page. Limited records may be retained where legally permitted or required, and backup copies expire through normal backup cycles."],
  ["Security", "We use encrypted network transport, authenticated sessions, database row-level security, role-based permissions, and audit records. No method is completely secure. Protect your password, keep your device secure, and report suspected account misuse promptly."],
  ["Children", "Advent Pro is a general spiritual-resource service and is not directed to children for the purpose of collecting personal information. A parent or guardian should supervise a child's use of account and community features. Contact us if you believe a child supplied personal data that should be removed."],
  ["International processing", "Supabase, Google, hosting providers, and other service providers may process information in countries other than yours. Their locations and legal protections may differ from those in your country."],
  ["Your choices", "You may use core offline reading without an account, sign out, change your display name or email, change your password, remove your comments where the feature allows, control app data through device settings, and request access, correction, or deletion subject to applicable law."],
  ["Policy changes", "We may update this policy when features, providers, or legal requirements change. We will revise the effective date and provide additional notice when a change materially affects how personal information is used."],
  ["Contact", "Send privacy questions, rights requests, and deletion requests to adventnurutech@gmail.com, through https://adventnurutech.xyz, or through the contact options on the app's About page."],
];
export default function PrivacyPage(){return <main className="legal-page"><h1>Advent Pro Privacy Policy</h1><p className="legal-date">Effective August 24, 2026</p><p>This policy explains how Advent Pro and Advent Nuru Tech process information in the mobile app, public website, and administration service.</p>{sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}<nav className="legal-links" aria-label="Advent Pro legal resources"><a href="/terms">Terms of Service</a><a href="/account-deletion">Request account deletion</a><a href="mailto:adventnurutech@gmail.com">Privacy contact</a></nav></main>}
