import { Ionicons } from "@expo/vector-icons";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { useAppTheme } from "@/hooks/use-app-theme";
import { diffText, getContribution, reviewContribution, type ContributionDetail } from "@/src/features/collaboration/studyCollaborationService";

export default function ContributionReviewScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { colors, fontFamily } = useAppTheme();
  const [item, setItem] = useState<ContributionDetail | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; void (async () => { try { const result = await getContribution(String(id)); if (active) setItem(result); } catch (error) { Alert.alert("Couldn’t open contribution", (error as Error).message); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [id]);
  const changes = useMemo(() => item ? diffText(item.base.plainText, item.proposed.plainText) : [], [item]);
  const changedLines = changes.filter((line) => line.type !== "same").length;
  const decide = async (decision: "accept"|"request_changes"|"decline") => { if (!item) return; if (decision === "request_changes" && !message.trim()) return Alert.alert("Explain what should change", "A clear note helps the contributor respond accurately."); setBusy(true); try { await reviewContribution(item.id, decision, message.trim()); Alert.alert(decision === "accept" ? "Changes accepted" : decision === "decline" ? "Contribution declined" : "Feedback sent", decision === "accept" ? "The improvements are now the official project version. Publish when ready." : "The contributor can see your review note.", [{ text: "Done", onPress: () => router.back() }]); } catch (error) { Alert.alert("Review not completed", (error as Error).message); } finally { setBusy(false); } };
  if (loading) return <View style={[styles.center, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.tint} /></View>;
  if (!item) return <View style={[styles.center, { backgroundColor: colors.background }]}><Text style={{ color: colors.text }}>Contribution not found.</Text></View>;
  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}><Stack.Screen options={{ headerShown: false }} />
      <View style={[styles.header, { backgroundColor: colors.card, borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()} style={styles.iconButton}><Ionicons name="arrow-back" size={22} color={colors.text} /></Pressable><View style={{ flex: 1 }}><Text style={[styles.headerTitle, { color: colors.text, fontFamily }]}>Review improvements</Text><Text style={[styles.headerSub, { color: colors.mutedText, fontFamily }]}>From {item.authorName} · {changedLines} changed sections</Text></View></View>
      <ScrollView contentContainerStyle={styles.content}>
        {item.isOutdated && <View style={styles.warning}><Ionicons name="warning-outline" size={23} color="#92400E" /><View style={{ flex: 1 }}><Text style={styles.warningTitle}>This contribution started from an older version</Text><Text style={styles.warningCopy}>It cannot be accepted over newer work. Ask the contributor to update their copy and send again.</Text></View></View>}
        <Text style={[styles.title, { color: colors.text, fontFamily }]}>{item.proposed.title}</Text>
        <View style={[styles.authorCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: `${colors.tint}12` }]}><Ionicons name="person-outline" size={23} color={colors.tint} /></View><View style={{ flex: 1 }}><Text style={[styles.author, { color: colors.text, fontFamily }]}>{item.authorName}</Text><Text style={[styles.message, { color: colors.mutedText, fontFamily }]}>{item.message || "Suggested improvements"}</Text><Text style={[styles.date, { color: colors.subtleText, fontFamily }]}>{new Date(item.createdAt).toLocaleString()}</Text></View></View>
        <View style={styles.legend}><View style={[styles.legendDot, { backgroundColor: "#DCFCE7" }]} /><Text style={[styles.legendText, { color: colors.mutedText }]}>Added</Text><View style={[styles.legendDot, { backgroundColor: "#FEE2E2" }]} /><Text style={[styles.legendText, { color: colors.mutedText }]}>Removed</Text></View>
        <View style={[styles.diffCard, { borderColor: colors.border, backgroundColor: colors.card }]}>{changes.map((line, index) => <View key={`${line.type}-${index}`} style={[styles.diffLine, line.type === "added" && styles.added, line.type === "removed" && styles.removed]}><Text style={[styles.symbol, { color: line.type === "added" ? "#166534" : line.type === "removed" ? "#991B1B" : colors.subtleText }]}>{line.type === "added" ? "+" : line.type === "removed" ? "−" : " "}</Text><Text style={[styles.diffText, { color: line.type === "added" ? "#166534" : line.type === "removed" ? "#991B1B" : colors.mutedText, fontFamily }]}>{line.text}</Text></View>)}</View>
        {item.canReview && item.status === "submitted" && <><Text style={[styles.reviewLabel, { color: colors.text, fontFamily }]}>Review note</Text><TextInput value={message} onChangeText={setMessage} multiline maxLength={500} placeholder="Optional when accepting; required when requesting changes" placeholderTextColor={colors.subtleText} style={[styles.reviewInput, { color: colors.text, borderColor: colors.border, backgroundColor: colors.card }]} /><Pressable disabled={busy || item.isOutdated} onPress={() => void decide("accept")} style={[styles.acceptButton, (busy || item.isOutdated) && { opacity: .4 }]}><Ionicons name="checkmark-circle-outline" size={21} color="#fff" /><Text style={styles.primaryText}>Accept improvements</Text></Pressable><View style={styles.secondaryRow}><Pressable disabled={busy} onPress={() => void decide("request_changes")} style={[styles.secondaryButton, { borderColor: "#D97706" }]}><Text style={{ color: "#B45309", fontWeight: "900" }}>Request changes</Text></Pressable><Pressable disabled={busy} onPress={() => void decide("decline")} style={[styles.secondaryButton, { borderColor: "#DC2626" }]}><Text style={{ color: "#DC2626", fontWeight: "900" }}>Decline</Text></Pressable></View></>}
        {item.status !== "submitted" && <View style={[styles.resultCard, { borderColor: colors.border }]}><Ionicons name={item.status === "accepted" ? "checkmark-circle" : "information-circle-outline"} size={23} color={item.status === "accepted" ? "#16A34A" : colors.tint} /><View style={{ flex: 1 }}><Text style={[styles.resultTitle, { color: colors.text }]}>{item.status.replace("_", " ")}</Text>{item.reviewMessage ? <Text style={[styles.resultCopy, { color: colors.mutedText }]}>{item.reviewMessage}</Text> : null}</View></View>}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { minHeight: 62, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 10, gap: 8 }, iconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, headerTitle: { fontSize: 15, fontWeight: "900" }, headerSub: { fontSize: 10, fontWeight: "700", marginTop: 2 }, content: { padding: 20, paddingBottom: 60 }, warning: { backgroundColor: "#FEF3C7", borderColor: "#F59E0B", borderWidth: 1, borderRadius: 15, padding: 13, flexDirection: "row", gap: 10, marginBottom: 16 }, warningTitle: { color: "#78350F", fontSize: 13, fontWeight: "900" }, warningCopy: { color: "#92400E", fontSize: 11, lineHeight: 16, marginTop: 3 }, title: { fontSize: 25, lineHeight: 32, fontWeight: "900" },
  authorCard: { borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: "row", alignItems: "center", gap: 11, marginTop: 14 }, avatar: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, author: { fontSize: 14, fontWeight: "900" }, message: { fontSize: 11, lineHeight: 16, marginTop: 2 }, date: { fontSize: 9, marginTop: 4 }, legend: { flexDirection: "row", alignItems: "center", gap: 6, marginVertical: 14 }, legendDot: { width: 14, height: 14, borderRadius: 4, marginLeft: 5 }, legendText: { fontSize: 10, fontWeight: "700" }, diffCard: { borderWidth: 1, borderRadius: 16, overflow: "hidden" }, diffLine: { flexDirection: "row", paddingHorizontal: 10, paddingVertical: 7 }, added: { backgroundColor: "#DCFCE7" }, removed: { backgroundColor: "#FEE2E2" }, symbol: { width: 20, fontSize: 13, fontWeight: "900" }, diffText: { flex: 1, fontSize: 12, lineHeight: 18 },
  reviewLabel: { fontSize: 13, fontWeight: "900", marginTop: 19, marginBottom: 7 }, reviewInput: { minHeight: 100, borderWidth: 1, borderRadius: 13, padding: 12, textAlignVertical: "top" }, acceptButton: { minHeight: 50, borderRadius: 14, backgroundColor: "#15803D", flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center", marginTop: 14 }, primaryText: { color: "#fff", fontWeight: "900" }, secondaryRow: { flexDirection: "row", gap: 9, marginTop: 9 }, secondaryButton: { flex: 1, minHeight: 47, borderWidth: 1, borderRadius: 13, alignItems: "center", justifyContent: "center" }, resultCard: { borderWidth: 1, borderRadius: 15, padding: 14, flexDirection: "row", gap: 11, marginTop: 15 }, resultTitle: { fontSize: 13, fontWeight: "900", textTransform: "capitalize" }, resultCopy: { fontSize: 11, lineHeight: 16, marginTop: 3 },
});
