import { Stack } from "expo-router";
import { Platform, ScrollView, StatusBar, StyleSheet, Text, View } from "react-native";
import { useAppTheme } from "@/hooks/use-app-theme";
import { useQuickFooter } from "@/src/context/QuickFooterContext";

const sections = [
  ["Account information", "You can read core resources without an account. If you create one, we process your email address, display name, account identifier, roles, authentication and session records, and account-security events. Supabase handles passwords and authentication tokens; Advent Pro does not receive your plaintext password."],
  ["Community and administrative content", "We process study and media comments, likes, comment reports, moderation status, content contributions, publication records, role assignments, deletion requests, and audit records. Your display name and visible comments are shown to other users. Reports, email addresses, role-management details, and audit records are limited to you or authorized administrators as appropriate."],
  ["Viewing activity and recommendations", "To count views, limit duplicate counts, rank popular content, and recommend studies, we process the study or media item viewed, timestamps, a random app session identifier, media watch duration, and your account identifier when signed in. Anonymous session identifiers are not intended to identify you by name, but they are still usage data."],
  ["Offline and device storage", "Songs, studies, Bible versions, search indexes, settings, daily-verse state, authentication sessions, and cached media details may be stored locally using the app database or device storage. Clearing app data or uninstalling removes local data, but it does not by itself delete synchronized account or community data."],
  ["Embedded media, support payments, and external services", "Advent Pro uses Supabase for authentication, database, synchronization, email delivery, and secure support-payment records. YouTube videos and Shorts play through an embedded YouTube player; Google or YouTube may receive network, device, cookie or similar identifier, and playback information under their own terms and privacy policy. Voluntary support payments use an embedded Paystack checkout. Paystack receives the email and payment information you submit under its privacy terms. Advent Pro stores the transaction reference, amount, currency, status, payment channel, timestamps, and limited app metadata, but does not store your M-Pesa PIN, card number, or CVV. Websites, calls, WhatsApp, and sharing use third-party services under their own policies."],
  ["How we use information", "We use information to operate accounts and community features, provide and synchronize content, count engagement, personalize or rank discovery, prevent spam and abuse, moderate reports, secure and administer the service, respond to support and deletion requests, and comply with legal obligations. We do not sell personal information or use it for third-party behavioral advertising."],
  ["When information is shared", "We disclose information to service providers that operate the service, to other users when you post public community content, when you deliberately share content through another app, when required by law, or when necessary to protect users, rights, and service security. Authorized administrators can access information needed for their assigned duties."],
  ["Retention and account deletion", "We keep information only as long as reasonably needed for the purposes above, including security, moderation, disputes, legal obligations, backups, and audit integrity. In-app deletion creates a pending request and signs you out; an authorized administrator or server process must complete deletion of the Supabase Auth account and associated personal data. Request deletion under Settings, Account & access, or through the public account-deletion page at adventnurutech.xyz. Limited records may be retained where legally permitted or required, and backup copies expire through normal backup cycles."],
  ["Security", "We use encrypted network transport, authenticated sessions, database row-level security, role-based permissions, and audit records. No method is completely secure. Protect your password, keep your device secure, and report suspected account misuse promptly."],
  ["Children", "Advent Pro is a general spiritual-resource service and is not directed to children for the purpose of collecting personal information. A parent or guardian should supervise a child's use of account and community features. Contact us if you believe a child supplied personal data that should be removed."],
  ["International processing", "Supabase, Google, hosting providers, and other service providers may process information in countries other than yours. Their locations and legal protections may differ from those in your country."],
  ["Your choices", "You may use core offline reading without an account, sign out, change your display name or email, change your password, remove your comments where the feature allows, control app data through device settings, and request access, correction, or deletion subject to applicable law."],
  ["Policy changes", "We may update this policy when features, providers, or legal requirements change. We will revise the effective date and provide additional notice when a change materially affects how personal information is used."],
  ["Contact", "Send privacy questions, rights requests, and deletion requests through https://adventnurutech.xyz or the call and WhatsApp options on the app's About page."],
];

export default function PrivacyPolicyScreen() {
  const { colors, size, fontFamily, darkMode } = useAppTheme(); const { reportScroll } = useQuickFooter();
  return <View style={[styles.container,{backgroundColor:colors.background}]}><Stack.Screen options={{headerShown:false}}/><StatusBar barStyle={darkMode?"light-content":"dark-content"} backgroundColor={colors.background}/>
    <ScrollView contentContainerStyle={styles.content} onScroll={e=>reportScroll(e.nativeEvent.contentOffset.y)} scrollEventThrottle={16}>
      <Text style={[styles.heading,{color:colors.text,fontSize:size(30),fontFamily}]}>Privacy Policy</Text>
      <Text style={[styles.date,{color:colors.mutedText,fontFamily}]}>Effective: August 25, 2026</Text>
      <Text style={[styles.paragraph,{color:colors.text,fontSize:size(15),fontFamily}]}>This policy explains how Advent Pro and Advent Nuru Tech process information when you use the mobile application, website, and administration services.</Text>
      {sections.map(([title,body])=><View key={title}><Text style={[styles.title,{color:colors.text,fontSize:size(20),fontFamily}]}>{title}</Text><Text style={[styles.paragraph,{color:colors.text,fontSize:size(15),fontFamily}]}>{body}</Text></View>)}
    </ScrollView></View>;
}
const styles=StyleSheet.create({container:{flex:1},content:{paddingHorizontal:24,paddingTop:Platform.OS==="ios"?70:52,paddingBottom:50},heading:{fontWeight:"800"},date:{marginTop:6,marginBottom:18},title:{fontWeight:"700",marginTop:22,marginBottom:8},paragraph:{lineHeight:24,marginBottom:10}});
