import { Stack } from "expo-router";
import { Platform, ScrollView, StatusBar, StyleSheet, Text, View } from "react-native";
import { useAppTheme } from "@/hooks/use-app-theme";
import { useQuickFooter } from "@/src/context/QuickFooterContext";

const sections=[
 ["Accounts and eligibility","You may use core reading features without an account. For account and community features, provide accurate information, keep your password and device secure, and report unauthorized access. You are responsible for activity under your account. Administrative roles are privileges that may be changed or revoked to protect the service."],
 ["Community rules","Comments, reports, likes, and other interactions must be respectful and lawful. Do not harass, threaten, impersonate, spam, manipulate engagement or view counts, post malicious links, spread deliberately harmful misinformation, or infringe another person's privacy or rights. Do not bypass security, scrape abusively, reverse engineer protected parts of the service, or disrupt availability."],
 ["Moderation","Advent Pro may review reports and may hide, edit, preserve, or remove comments or other material; restrict interactions; and suspend accounts when reasonably necessary to enforce these terms, protect users, comply with law, or secure the service. Moderation and automated spam controls may not identify every problem. Report concerns through the available reporting or contact tools."],
 ["Contributions and licence","You retain rights you hold in material you submit. You grant Advent Pro and Advent Nuru Tech a worldwide, non-exclusive, royalty-free licence to host, store, reproduce, format, adapt for technical display, translate, distribute, and display that material as needed to operate, improve, and promote the service. You confirm you have the rights and permissions needed to submit it. Editors may correct, reject, unpublish, or remove contributed resources."],
 ["Spiritual resources","Hymns, Bible resources, studies, videos, Shorts, recommendations, and community content are provided for worship, education, and personal study. Contributor and linked-media views do not necessarily represent Advent Pro. Verify important information and do not use the service as medical, legal, financial, emergency, or professional advice."],
 ["YouTube and external services","Some media is hosted by YouTube and plays through its embedded player, so YouTube's terms and privacy practices also apply. Links for websites, donations, PayPal or other payment services, calls, WhatsApp, and device sharing take you to third-party services. Advent Pro does not control their availability, content, charges, security, or privacy practices. Review their terms before using them."],
 ["Engagement and recommendations","View, like, share, and comment totals and personalized or popular-study rankings are service features. Counts may be delayed, deduplicated, moderated, reset, or corrected and are not guaranteed to be exact. Do not attempt to inflate or manipulate them."],
 ["Copyright and reports","Respect authors, ministries, publishers, video owners, and applicable licences. Report infringement or content concerns through adventnurutech.xyz or the contact options in About, identifying the material and the basis for your request. We may remove or restrict disputed material while reviewing it."],
 ["Offline use and updates","Downloaded or bundled content may remain available offline. When connected, the app may receive new resources, corrections, withdrawals, rankings, media details, and compatibility or security changes without an app-store release. Application changes may still require an app-store update, and online or embedded-media features require a suitable connection."],
 ["Account deletion and termination","You may stop using the service and request account deletion. A request is queued for processing and is not completed merely by uninstalling the app. We may retain limited security, legal, audit, dispute, and backup records where permitted or required. We may restrict or terminate access that violates these terms, creates risk, or must be restricted by law."],
 ["Service availability and disclaimers","The service is provided on an as-available basis. We do not promise uninterrupted access, permanent availability of third-party videos, or that every resource, translation, recommendation, count, or community post is complete, accurate, or error-free. Keep copies of important original contributions."],
 ["Limitation of liability","To the extent permitted by law, Advent Pro and Advent Nuru Tech are not liable for indirect, incidental, special, consequential, or punitive loss arising from use of or inability to use the service. Nothing in these terms excludes rights or liability that cannot legally be excluded."],
 ["Changes and contact","We may update these terms as features, providers, or legal requirements change. We will revise the effective date and provide reasonable additional notice for material changes. Questions, reports, and account requests can be submitted at https://adventnurutech.xyz or through the contact options in the app's About page."],
];
export default function TermsOfUseScreen(){const{colors,size,fontFamily,darkMode}=useAppTheme();const{reportScroll}=useQuickFooter();return <View style={[s.container,{backgroundColor:colors.background}]}><Stack.Screen options={{headerShown:false}}/><StatusBar barStyle={darkMode?"light-content":"dark-content"} backgroundColor={colors.background}/><ScrollView contentContainerStyle={s.content} onScroll={e=>reportScroll(e.nativeEvent.contentOffset.y)} scrollEventThrottle={16}><Text style={[s.heading,{color:colors.text,fontSize:size(30),fontFamily}]}>Terms of Service</Text><Text style={[s.date,{color:colors.mutedText,fontFamily}]}>Effective: August 24, 2026</Text><Text style={[s.text,{color:colors.text,fontSize:size(15),fontFamily}]}>By using Advent Pro, you agree to these terms. If you do not agree, do not create an account or use the online services. Core content may remain available offline where installed.</Text>{sections.map(([title,body])=><View key={title}><Text style={[s.title,{color:colors.text,fontSize:size(20),fontFamily}]}>{title}</Text><Text style={[s.text,{color:colors.text,fontSize:size(15),fontFamily}]}>{body}</Text></View>)}</ScrollView></View>}
const s=StyleSheet.create({container:{flex:1},content:{paddingHorizontal:24,paddingTop:Platform.OS==="ios"?70:52,paddingBottom:50},heading:{fontWeight:"800"},date:{marginTop:6,marginBottom:18},title:{fontWeight:"700",marginTop:22,marginBottom:8},text:{lineHeight:24,marginBottom:10}});
